services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    container_name: landscape-mlflow

    ports:
      - "8080:5000"

    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlartifacts:/mlflow/mlartifacts

    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlruns/mlflow.db
      --serve-artifacts
      --artifacts-destination /mlflow/mlartifacts

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: landscape-api

    ports:
      - "8000:8000"

    environment:
      - TRITON_URL=triton:8000

    depends_on:
      - triton

  triton:
    image: nvcr.io/nvidia/tritonserver:24.10-py3
    container_name: landscape-triton

    ports:
      - "8001:8000"
      - "8002:8001"
      - "8003:8002"

    volumes:
      - ./triton_model_repository:/models

    command: >
      tritonserver
      --model-repository=/models
      --model-control-mode=poll
      --repository-poll-secs=5
